version: '3'

services:
  db:
    container_name: tzkt-db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  api:
    container_name: tzkt-api
    restart: always
    image: mavrykdynamics/tzkt-api:latest
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: host=db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
    ports:
      - 0.0.0.0:5000:5000

  sync:
    container_name: tzkt-sync
    restart: always
    image: mavrykdynamics/tzkt-sync:latest
    environment:
      ConnectionStrings__DefaultConnection: host=db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5001
      MavrykNode__Endpoint: ${NODE_RPC:-https://basenet.mavryk.network/}
    depends_on:
      - db
    ports:
      - 0.0.0.0:5001:5001

volumes:
  postgres:
